<?php

namespace Blog\ServingBundle\Repository;

/**
 * BiographieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiographieRepository extends \Doctrine\ORM\EntityRepository
{
}
